// Backend API client + live-progress map.
// All HTTP calls to the Flask backend funnel through here so retries,
// timeouts, and base-URL resolution stay in one place.

import { useEffect, useState } from "react";
import type { AnimResult, ParsedProblem } from "../types";

export const flaskBase = (): string =>
  (import.meta.env.VITE_FLASK_URL as string | undefined) || "http://localhost:5000";

// ─────────────────────────────────────────────────────────────
// Live progress: pollJob writes the latest backend-reported progress
// into a module-level Map keyed by topic id, so React components can
// read real numbers via useLiveProgress() during a render.
// ─────────────────────────────────────────────────────────────

const _liveProgress = new Map<string, number>();
const _liveListeners = new Set<() => void>();
function _emitLive() { _liveListeners.forEach((cb) => cb()); }

export function setLiveProgress(topicId: string, value: number | null) {
  if (value === null) _liveProgress.delete(topicId);
  else _liveProgress.set(topicId, value);
  _emitLive();
}

export function useLiveProgress(topicId: string | null): number | null {
  const [, force] = useState(0);
  useEffect(() => {
    const cb = () => force((n) => n + 1);
    _liveListeners.add(cb);
    return () => { _liveListeners.delete(cb); };
  }, []);
  if (!topicId) return null;
  return _liveProgress.has(topicId) ? _liveProgress.get(topicId)! : null;
}

// ─────────────────────────────────────────────────────────────
// pollJob — the workhorse. Polls /status/<jobId> every 350ms until the
// backend reports done/error or the deadline passes (200s, slightly
// longer than the worker's 180s manim budget).
// ─────────────────────────────────────────────────────────────

export async function pollJob(
  flaskUrl: string,
  jobId: string,
  topicId: string,
): Promise<AnimResult> {
  const deadline = Date.now() + 200_000;
  try {
    while (Date.now() < deadline) {
      await new Promise((r) => setTimeout(r, 350));
      const statusRes = await fetch(`${flaskUrl}/status/${jobId}`);
      if (!statusRes.ok) continue;
      const job = await statusRes.json();
      if (typeof job.progress === "number") {
        setLiveProgress(topicId, job.progress);
      }
      if (job.status === "done" && job.url) {
        return { videoUrl: `${flaskUrl}${job.url}`, status: "ready" };
      }
      if (job.status === "error") {
        return {
          videoUrl: `placeholder://${topicId}`,
          status: "error",
          error: job.error || "render failed",
        };
      }
    }
    return {
      videoUrl: `placeholder://${topicId}`,
      status: "error",
      error: "render timed out after 200s",
    };
  } finally {
    setLiveProgress(topicId, null);
  }
}

// ─────────────────────────────────────────────────────────────
// OCR — image / PDF → text via Gemini vision (fallback to mock if the
// backend is unreachable, e.g. GEMINI_API_KEY not configured).
// ─────────────────────────────────────────────────────────────

export async function ocrFile(file: File): Promise<{ text: string }> {
  const flaskUrl = flaskBase();
  const fd = new FormData();
  fd.append("file", file);
  try {
    const res = await fetch(`${flaskUrl}/api/ocr`, { method: "POST", body: fd });
    if (!res.ok) {
      const detail = await res.text().catch(() => "");
      throw new Error(`/api/ocr ${res.status}: ${detail.slice(0, 200)}`);
    }
    const data = await res.json();
    if (typeof data.text !== "string") throw new Error("/api/ocr: missing text field");
    return { text: data.text };
  } catch (e) {
    console.warn("OCR fell back to mock:", e);
    return {
      text: `[Mock OCR output from ${file.name}]\n\nFind the volume of the solid generated by revolving the region bounded by y = x², y = 0, and x = 2 about the y-axis.\n\n(Backend /api/ocr is unreachable — set GEMINI_API_KEY in backend/.env and restart the server.)`,
    };
  }
}

// ─────────────────────────────────────────────────────────────
// Universal parser — classifies math vs DSA on the backend and routes
// to the matching parser. Used by paste page + inline note animate.
// ─────────────────────────────────────────────────────────────

export async function parseProblemV2(rawText: string): Promise<ParsedProblem> {
  const res = await fetch(`${flaskBase()}/api/parse-problem-v2`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ rawText }),
  });
  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    const detail = err.detail || err.error || `HTTP ${res.status}`;
    throw new Error(detail);
  }
  return res.json();
}

// ─────────────────────────────────────────────────────────────
// Fetch a LeetCode problem statement by URL via the backend's GraphQL
// proxy. Lets the user paste a leetcode.com URL instead of prose.
// ─────────────────────────────────────────────────────────────

export async function fetchLeetCodeProblem(
  url: string,
): Promise<{ title: string; rawText: string; sampleInput: string; difficulty: string }> {
  const res = await fetch(`${flaskBase()}/api/fetch-leetcode`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ url }),
  });
  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    throw new Error(err.detail || err.error || `HTTP ${res.status}`);
  }
  return res.json();
}

// ─────────────────────────────────────────────────────────────
// Conversational follow-up parser — sends the prior parsed result so
// the model can apply the user's tweak ("now with [3,1,4]" / "show me
// with X instead" / "explain step 3 slower") without re-pasting.
// ─────────────────────────────────────────────────────────────

export async function parseFollowUp(
  prior: ParsedProblem,
  followUp: string,
): Promise<ParsedProblem> {
  const res = await fetch(`${flaskBase()}/api/parse-followup`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ prior, followUp }),
  });
  if (!res.ok) {
    const err = await res.json().catch(() => ({}));
    const detail = err.detail || err.error || `HTTP ${res.status}`;
    throw new Error(detail);
  }
  return res.json();
}
